package pojo;
// Generated 2 Dec 2022, 14:08:10 by Hibernate Tools 6.1.3.Final

/**
 * Zoologicos generated by hbm2java
 */
public class Zoologicos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String ciudad;
	private int anyoFundacion;

	public Zoologicos() {
	}

	public Zoologicos(String nombre, String ciudad, int anyoFundacion) {
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.anyoFundacion = anyoFundacion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public int getAnyoFundacion() {
		return this.anyoFundacion;
	}

	public void setAnyoFundacion(int anyoFundacion) {
		this.anyoFundacion = anyoFundacion;
	}

}
