package main.java.pojo;

// default package
// Generated 9 Dec 2022, 14:12:51 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Continentes generated by hbm2java
 */

public class Continente implements java.io.Serializable {

	private int id;
	private String nombre;
	private int poblacion;
	@OneToMany(targetEntity=Pais.class)
	@JoinColumn(name="continente_id")
	private Set paises = new HashSet(0);

	public Continente() {
	}

	public Continente(int id, String nombre, int poblacion) {
		this.id = id;
		this.nombre = nombre;
		this.poblacion = poblacion;
	}

	public Continente(int id, String nombre, int poblacion, Set paiseses) {
		this.id = id;
		this.nombre = nombre;
		this.poblacion = poblacion;
		this.paiseses = paiseses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(int poblacion) {
		this.poblacion = poblacion;
	}

	public Set getPaiseses() {
		return this.paiseses;
	}

	public void setPaiseses(Set paiseses) {
		this.paiseses = paiseses;
	}

}
