package main.java.pojo;

// default package
// Generated 9 Dec 2022, 14:12:51 by Hibernate Tools 6.1.3.Final

/**
 * Paises generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private int id;
	private Continente continentes;
	private String nombre;
	private int poblacion;
	private String jefeEstado;

	public Pais() {
	}

	public Pais(int id, Continente continentes, String nombre, int poblacion) {
		this.id = id;
		this.continentes = continentes;
		this.nombre = nombre;
		this.poblacion = poblacion;
	}

	public Pais(int id, Continente continentes, String nombre, int poblacion, String jefeEstado) {
		this.id = id;
		this.continentes = continentes;
		this.nombre = nombre;
		this.poblacion = poblacion;
		this.jefeEstado = jefeEstado;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Continente getContinentes() {
		return this.continentes;
	}

	public void setContinentes(Continente continentes) {
		this.continentes = continentes;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(int poblacion) {
		this.poblacion = poblacion;
	}

	public String getJefeEstado() {
		return this.jefeEstado;
	}

	public void setJefeEstado(String jefeEstado) {
		this.jefeEstado = jefeEstado;
	}

}
